export const dataTypes: Record<string, string> = {
    'email': 'A email adress',
    'first_name': 'A first name',
    'last_name': 'A last name',
    'full_name': 'A full name, including first and last name',
    'ip_address': 'An IP address',
    'user_agent': 'A user-agent that was saved as part as a log file',
    'user_language': 'A language that is used for browsing the platform',
    'cookie': 'A cookie that was saved',
    'follower': 'A follower for the user',
    'account_following': 'Another account that the user is following',
    'blocked_account': 'Another account that the user has blocked',
    'hashtag_following': 'A hashtag the user is following',
    'ad_interest': 'An ad interest that was flagged by the system for the user',
    'telephone_number': 'A telephone number',
    'comment': 'A comment made by the user',
    'device': 'A device that was used by the user on the platform',
    'username': 'A username that is used for a particular platform',
    'place_of_residence': 'A place (city, town, village, etc.) where the user resides',
    'address': 'A full adress, including street, number, ZIP-code and eventual state',
    'country': 'The country where a user resides',
    'like': 'A like thas been placed on a particular post',
    'login_instance': 'A saved instance of the user logging in',
    'logout_instance': 'A saved instance of the user logging out',
    'photo': 'A photo',
    'message': 'A message by the user, to another user',
    'gender': 'A gender',
    'profile_picture': 'A profile picture',
    'date_of_birth': 'A birth date',
    'join_date': 'The date on which the user joined a platform',
    'search_query': 'A search query by the user',
    'post_seen': 'A post that the user has seen',
    'privacy_setting': 'A privacy setting for the user',
    'uploaded_contact': 'A telephone contact that has been uploaded by the user',
    'session': 'A saved cookie with possibly extra information',
    'peer_group': 'A categorisation of the peer group you belong to',
    'employment': 'A job held currently or in the past',
    'visited_page': 'An in-site visited page',
    'off_site_activity': 'Recorded activity outside of the platform website',
    'event_response': 'Response to an event invitation',
    'timezone': 'Timezone associated with the user',
    'currency': 'Currency associated with the user',
    'education_experience': 'An education experience held currently or in the past',
    'registration_date': 'Registration date for the platform',
    'mobile_device': 'A mobile device associated with the platform',
    'inference': 'An inference about an individual',
    'played_song': 'A song that has been played by the user',
};

const request = {
    requestId: "1",
    createdAt: new Date(),
    expectedCompletion: new Date(),
    completedAt: new Date(),
    isCompleted: true,
    dataRequested: Object.keys(dataTypes),
}

export default request;